version: "3"

x-default-options: &default-options
  tty: true
  logging:
    options:
      max-size: '10m'
      max-file: '3'
      
services:
    server:
        build:
            context: server
            dockerfile: Dockerfile.dev
        container_name: transportmap-server
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - 3001:3001
        volumes:
            - ./server:/app:delegated
            - ./server/static:/static:delegated
            # - ../hafas-client:/app/node_modules/hafas-client
            # - ./api/src/modules/vehicle/static:/app/dist/modules/vehicle/static
            - /app/node_modules
            # - /app/data
        env_file:
            - ./server/.env/local.env
        networks:
            - transportmap
        <<: *default-options

    postgres:
        image: "postgres:15.2-alpine"
        container_name: transportmap-postgres
        ports:
            - 5432:5432
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: transportmap
            POSTGRES_PASSWORD: transportmap
            POSTGRES_DB: transportmap
        networks:
            - transportmap

    app:
        build:
            context: client
            dockerfile: Dockerfile.dev
        extra_hosts:
            - "host.docker.internal:host-gateway"
        container_name: transportmap-app
        volumes:
            - ./client:/app:delegated
            - /app/node_modules
            - /app/dist
        ports:
            - 3000:3000
        networks:
            - transportmap

    redis:
        image: "redis:7.0.3-alpine"
        container_name: transportmap-redis
        ports:
            - 6379:6379
        networks:
            - transportmap

    osrm:
        image: "ghcr.io/project-osrm/osrm-backend:v5.27.1"
        command: osrm-routed --algorithm mld /data/map-data/map.osrm
        container_name: osrm
        ports:
            - 5000:5000
        volumes:
            - ./osm:/data:delegated
        networks:
            - transportmap

    redis-commander:
        container_name: transportmap-redis-commander
        image: ghcr.io/joeferner/redis-commander:latest
        restart: always
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - 8081:8081
        networks:
            - transportmap

volumes:
    redis-data:
    elastic-data:

networks:
    transportmap: