name: Publish Docker image
on:
    push:
        tags:
            - v*

jobs:
    push_app_to_registry:
        name: build apps/transportmap
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
            - name: Cache Docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-app-buildx
                  restore-keys: |
                      ${{ runner.os }}-app-buildx
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: hybridfox/transportmap-app
                  tags: |
                      type=semver,pattern={{version}}
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push to Docker Hub
              uses: docker/build-push-action@v4
              with:
                  push: true
                  context: .
                  file: ./apps/transportmap/Dockerfile
                  platforms: linux/amd64
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
            - name: Move cache
              run: |
                  rm -rf /tmp/.buildx-cache
                  mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    push_api_to_registry:
        name: build apps/api
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            # https://github.com/docker/setup-buildx-action
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
            - name: Cache Docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-api-buildx
                  restore-keys: |
                      ${{ runner.os }}-api-buildx
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: hybridfox/transportmap-api
                  tags: |
                      type=semver,pattern={{version}}
            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push to Docker Hub
              uses: docker/build-push-action@v4
              with:
                  push: true
                  context: .
                  file: ./apps/api/Dockerfile
                  platforms: linux/amd64
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
            - name: Move cache
              run: |
                  rm -rf /tmp/.buildx-cache
                  mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    deploy:
        needs: [push_app_to_registry, push_api_to_registry]
        runs-on: ubuntu-latest
        steps:
            - name: curl
              uses: wei/curl@v1
              with:
                  args: -X POST ${{ secrets.RANCHER_DEPLOY_URL }}
